spring:  # ??? ?? ?? ??
  main:
    allow-bean-definition-overriding: true  # ? ?? ?????? ???? ??
  datasource:  # ?????? ?? ??
    url: jdbc:mysql://localhost:3306/wanted?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC ???? ???
  jpa:  # JPA ??
    show-sql: true  # SQL ?? ?? ??
    hibernate:  # ?????? ??
      ddl-auto: update  # ?????? ??? ?? ?? ?? (update)
    properties:  # ???? ?????? ??
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect  # MySQL ?????? ??
    generate-ddl: true  # DDL ?? ?? ??


server:  # ?? ? ?? ??
  port: 8080  # ? ?? ?? ??
  servlet:
    context-path: /api  # ??? ???? ?? ??
  error:
    include-message: always  # ?? ??? ??? ?? ??

#jwt:  # JWT ??
#  secret:
#    key: r5u8x/A?D(G+KbPeSgVkYp3s6v9y$B&E  # JWT ??? ?

logging:  # ?? ??
  level:
    root: info  # ??? ?? ?? ??

springdoc:  # SpringDoc ?? (OpenAPI ? Swagger UI ??)
  version: 1.0  # SpringDoc ??
  api-docs:
    path: /  # API ?? ?? ??
  default-consumes-media-type: application/json;charset=UTF-8  # ?? ?? ??? ?? ??
  default-produces-media-type: application/json;charset=UTF-8  # ?? ?? ??? ?? ??
  swagger-ui:  # Swagger UI ??
    operations-sorter: alpha  # ?? ?? ?? ?? (????)
    tags-sorter: alpha  # ?? ?? ?? ?? (????)
    path: /swagger-ui.html  # Swagger UI ?? ??
    disable-swagger-default-url: true  # ?? Swagger UI URL ???? ??
    display-query-params-without-oauth2: true  # OAuth2 ?? ?? ???? ?? ??
    doc-expansion: none  # ?? ?? ??

  paths-to-match:
    /**

app:  # ?????? ??
  cors:  # CORS(Cross-Origin Resource Sharing) ??
    allowedOrigins: http://localhost:3000, http://localhost:8080, https://dodum.xyz  # ??? ??? ??


#springboot:  # Spring Boot ??
#  jwt:
#    secret: flature!@#  # JWT ??? ?
